# Generated by Django 3.0 on 2019-12-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='apellidos',
            field=models.CharField(max_length=255, verbose_name='Apellidos del Autor'),
        ),
    ]
